# Generated by Django 3.0 on 2021-10-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
